# -*- coding: utf-8 -*-
"""
Created on Sun Sep 20 12:14:16 2020

@author: brian
"""
import json
    
ixp_source = json.load(open("ix.json",'r', encoding='utf-8'))
all_list = []
whitelist = [
        'angonix', 
        'ANIX - Albanian Neutral Internet eXchange', 
        'ArmIX', 
        'BALT-IX', 
        'BCIX', 
        'B-IX', 
        'BKNIX', 
        'CAIX', 
        'ChIX', 
        'CIX', 
        'CNX', 
        'DE-CIX Dallas', 
        'DE-CIX Delhi', 
        'DE-CIX Frankfurt',
        'DE-CIX Hamburg', 
        'DE-CIX Istanbul',
        'DE-CIX Kolkata', 
        'DE-CIX Madrid', 
        'DE-CIX Marseille', 
        'DE-CIX Mumbai', 
        'DE-CIX Munich', 
        'DE-CIX New York', 
        'DE-CIX Palermo', 
        'EPIX.Katowice', 
        'EPIX.Warszawa-KIX', 
        'EVIX', 
        'GrenoblIX', 
        'Hopus', 
        'HOUIX', 
        'IIX-Bali', 
        'IIX-Jogja', 
        'IX.br (PTT.br) Belém',
        'IX.br (PTT.br) Belo Horizonte',
        'IX.br (PTT.br) Brasília',
        'IX.br (PTT.br) Campina Grande',
        'IX.br (PTT.br) Campinas',
        'IX.br (PTT.br) Campo Grande',
        'IX.br (PTT.br) Cascavel',
        'IX.br (PTT.br) Caxias do Sul',
        'IX.br (PTT.br) Cuiabá',
        'IX.br (PTT.br) Curitiba',
        'IX.br (PTT.br) Florianópolis',
        'IX.br (PTT.br) Fortaleza',
        'IX.br (PTT.br) Foz do Iguaçu',
        'IX.br (PTT.br) Goiânia',
        'IX.br (PTT.br) João Pessoa',
        'IX.br (PTT.br) Lajeado',
        'IX.br (PTT.br) Londrina',
        'IX.br (PTT.br) Maceió',
        'IX.br (PTT.br) Manaus',
        'IX.br (PTT.br) Maringá',
        'IX.br (PTT.br) Natal',
        'IX.br (PTT.br) Porto Alegre',
        'IX.br (PTT.br) Recife',
        'IX.br (PTT.br) Rio de Janeiro',
        'IX.br (PTT.br) Salvador',
        'IX.br (PTT.br) Santa Maria',
        'IX.br (PTT.br) São José do Rio Preto',
        'IX.br (PTT.br) São José dos Campos',
        'IX.br (PTT.br) São Luís',
        'IX.br (PTT.br) São Paulo',
        'IX.br (PTT.br) Teresina',
        'IX.br (PTT.br) Vitória',
        'IX.LODZ.PL', 
        'IXPN Lagos', 
        'JPIX OSAKA', 
        'JPIX TOKYO', 
        'JPNAP Osaka', 
        'JPNAP Tokyo', 
        'KAZ-GOV-IX', 
        'LONAP', 
        'LyonIX', 
        'MASS-IX', 
        'MICE', 
        'MIX-IT', 
        'MUS-IX', 
        'NetIX', 
        'NYIIX', 
        'NYIIX Los Angeles', 
        'NYIIX Philadelphia', 
        'PhOpenIX-Manila',
        'QIX', 
        'RED-IX', 
        'RIX', 
        'SAIX', 
        'SGIX', 
        'SIX Seattle', 
        'SIX Seattle (Jumbo)', 
        'SIX SI', 
        'STHIX - Gothenburg', 
        'STHIX - Stockholm', 
        'STHIX - Sundsvall', 
        'STHIX - Umeå', 
        'TahoeIX', 
        'TIX Tanzania - Dar es Salaam', 
        'TN-IX', 
        'TorIX', 
        'TPIX Warsaw', 
        'TWIX', 
        'UAE-IX', 
        'UA-IX', 
        'VarnaIX',
        'YAR-IX'
        'YEGIX', 
        'YXEIX', 
        'YYCIX'
        ]
for ixp_dict in ixp_source['data']:
    if ixp_dict['url_stats'] != '' and ixp_dict['name'] not in whitelist:
        all_list.append(ixp_dict)

'''
with open('new_ix.json', 'w') as fp:
    json.dump(all_list, fp)
'''